name: key_value_store_web
description: A multiplatform key-value store implementation for web.
version: 1.0.0
homepage: https://github.com/roughike/multiplatform_key_value_store
author: Iiro Krankka <iiro.krankka@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  key_value_store:
    path: ../key_value_store

dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.1
  test: ^1.0.0
  mockito: ^3.0.0
